// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductShop.Models;

#nullable disable

namespace ProductShop.Migrations
{
    [DbContext(typeof(RecordContext))]
    [Migration("20240419142338_HOT4")]
    partial class HOT4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductShop.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("ProductShop.Models.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecordName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecordId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            ArtistName = "Andy William",
                            ImageFileName = "andy_williams__youve_got_a_friend.jpg",
                            Price = 15m,
                            RecordName = "You've Got A Friend"
                        },
                        new
                        {
                            RecordId = 2,
                            ArtistName = "Dean Martin",
                            ImageFileName = "dean_martin__gentle_on_my_mind.jpg",
                            Price = 25m,
                            RecordName = "Gentle On My Mind"
                        },
                        new
                        {
                            RecordId = 3,
                            ArtistName = "Frank Sinatra",
                            ImageFileName = "frank_sinatra__sinatras_sinatra.jpg",
                            Price = 30m,
                            RecordName = "Sinatra's Sinatra"
                        },
                        new
                        {
                            RecordId = 4,
                            ArtistName = "Paul Anka",
                            ImageFileName = "paul_anka__anka.jpg",
                            Price = 10m,
                            RecordName = "Anka"
                        },
                        new
                        {
                            RecordId = 5,
                            ArtistName = "Perry Como",
                            ImageFileName = "perry_como__its_impossible.jpg",
                            Price = 17m,
                            RecordName = "It's Impossible"
                        });
                });

            modelBuilder.Entity("ProductShop.Models.Purchase", b =>
                {
                    b.HasOne("ProductShop.Models.Record", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });
#pragma warning restore 612, 618
        }
    }
}
